### ISSUE TITLE
Unclear (to me) on how to make this work

### ISSUE THREAD

**Issue by rduivenvoorde** [Oslandia/labelconnector#14] opened 2019-06-21 07:06 UTC
Having a simple lin (highway) shape, I thought to test the plugin.

So opened the shape (without saving it to a project...) and added normal labels.
Then tried to change them to 'connected labels' but did not see something happen.
Then removed labels and tried again to use the 'connected labels', but only see this now:

2019-06-21T08:56:57     CRITICAL    LabelConnector already exists : If you want to add a new LabelConnector on the style, please remove the comment in the expression first.

BUT: I cannot find  "the comment in the expression".
It could also have something to do with not having saved the project first?
Happy to sent you the (demo) shape.

**Comment by haubourg** [comment] 2019-06-21 07:11
Hi Richard! Happy to have a first user :)




>  It could also have something to do with not having saved the project first?

I don't think so. Are you testing in master? There is something broken with moving or editing labels independant from this plugin. I confirmed it yesterday and was about to raise an issue upstream. 

I'll make a video demo too so that you can the expected behavior. 
And for the context, this plugin is really here to provide a bad temporary solution before having native connectors in the core. I really hope we'll find support for that very long standing issue

**Comment by haubourg** [comment] 2019-07-09 16:40
> 2019-06-21T08:56:57 CRITICAL LabelConnector already exists : If you want to add a new LabelConnector on the style, please remove the comment in the expression first.

this is a duplicate of #19

**Comment by haubourg** [comment] 2019-07-15 16:15
That should be solved in most recent version. Please reopen if necessary

**Closed as completed by haubourg** 2019-07-15 16:15 UTC
Labels: bug
